version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - JWT_SECRET=97791d4db2aa5f689c3cc39356ce35762f0a73aa70923039d8ef72a2840a1b02
    command: >
      sh -c "alembic upgrade head &&
             python scripts/seed.py &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000"
